'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Form={make:string;model:string;year:string;vin:string;registration_number:string;license_region:string;notes:string;competition_number:string;vehicle_type:string;class_name:string;series_name:string};
const empty:Form={make:'',model:'',year:'',vin:'',registration_number:'',license_region:'',notes:'',competition_number:'',vehicle_type:'',class_name:'',series_name:''};

export default function EditVehicle(){
 const [vehicleId,setVehicleId]=useState(''); const [form,setForm]=useState<Form>(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient(); const {data:{user},error:ue}=await db.auth.getUser(); if(ue)throw ue; if(!user)throw new Error('Please sign in'); const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle(); if(ae)throw ae; if(!a)throw new Error('Login is not linked to a Core Person'); const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle(); if(me)throw me; if(!m)throw new Error('No active team membership found'); const {data:v,error:ve}=await db.from('vehicles').select('id,make,model,year,vin,registration_number,license_region,notes').eq('organisation_id',m.organisation_id).limit(1).maybeSingle(); if(ve)throw ve; if(!v)throw new Error('No vehicle found'); setVehicleId(v.id); const {data:r,error:re}=await db.from('raceiq_vehicle_profiles').select('competition_number,vehicle_type,class_name,series_name').eq('vehicle_id',v.id).maybeSingle(); if(re)throw re; setForm({make:v.make||'',model:v.model||'',year:v.year?.toString()||'',vin:v.vin||'',registration_number:v.registration_number||'',license_region:v.license_region||'',notes:v.notes||'',competition_number:r?.competition_number||'',vehicle_type:r?.vehicle_type||'',class_name:r?.class_name||'',series_name:r?.series_name||''});}catch(e:any){setError(e.message||'Unable to load vehicle')}finally{setLoading(false)}})()},[]);
 const change=(k:keyof Form,v:string)=>setForm(f=>({...f,[k]:v}));
 const save=async()=>{try{setSaving(true);setMessage('');setError('');const db=createClient(); const {error:ve}=await db.from('vehicles').update({make:form.make||null,model:form.model||null,year:form.year?Number(form.year):null,vin:form.vin||null,registration_number:form.registration_number||null,license_region:form.license_region||null,notes:form.notes||null,updated_at:new Date().toISOString()}).eq('id',vehicleId); if(ve)throw ve; const {error:re}=await db.from('raceiq_vehicle_profiles').update({competition_number:form.competition_number||null,vehicle_type:form.vehicle_type||null,class_name:form.class_name||null,series_name:form.series_name||null,updated_at:new Date().toISOString()}).eq('vehicle_id',vehicleId); if(re)throw re; setMessage('Vehicle details saved.');}catch(e:any){setError(e.message||'Unable to save vehicle')}finally{setSaving(false)}};
 const input=(label:string,key:keyof Form,type='text')=><label style={{display:'block',marginBottom:12}}><span className="muted" style={{display:'block',marginBottom:5}}>{label}</span><input type={type} value={form[key]} onChange={e=>change(key,e.target.value)} style={{width:'100%',maxWidth:320}}/></label>;
 if(loading)return <div className="card"><h3>Loading vehicle…</h3></div>;
 return <><div className="top"><div><div className="eyebrow">Garage / Vehicle / Edit</div><h1>Edit Vehicle Details</h1><div className="muted">Permanent vehicle and motorsport identity information</div></div></div>{error&&<p className="data-note">{error}</p>}<section className="grid"><div className="card"><div className="card-label">MOTORSPORT IDENTITY</div><h3>Competition</h3>{input('Competition Number','competition_number')}{input('Vehicle Type','vehicle_type')}{input('Class','class_name')}{input('Series','series_name')}</div><div className="card"><div className="card-label">CORE VEHICLE</div><h3>Vehicle Identity</h3>{input('Make / Manufacturer','make')}{input('Model','model')}{input('Year','year','number')}{input('VIN / Chassis Number','vin')}</div><div className="card"><div className="card-label">REGISTRATION</div><h3>Registration</h3>{input('Registration Number','registration_number')}{input('Region','license_region')}</div><div className="card"><div className="card-label">NOTES</div><h3>Vehicle Notes</h3><textarea value={form.notes} onChange={e=>change('notes',e.target.value)} rows={6} style={{width:'100%'}}/></div></section><div className="actions"><Link className="btn" href="/garage/vehicle">Cancel</Link><button className="btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save Vehicle'}</button>{message&&<span className="muted">{message}</span>}</div></>;
}
