'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Form={make:string;model:string;year:string;vin:string;logbook_number:string;notes:string;vehicle_type:string;class_name:string;series_name:string};
const empty:Form={make:'',model:'',year:'',vin:'',logbook_number:'',notes:'',vehicle_type:'',class_name:'',series_name:''};

export default function EditVehicle(){
 const [vehicleId,setVehicleId]=useState(''); const [imageAssetId,setImageAssetId]=useState(''); const [assets,setAssets]=useState<any[]>([]); const [form,setForm]=useState<Form>(empty); const [raceNumber,setRaceNumber]=useState('Not recorded'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient(); const {data:{user},error:ue}=await db.auth.getUser(); if(ue)throw ue; if(!user)throw new Error('Please sign in'); const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle(); if(ae)throw ae; if(!a)throw new Error('Login is not linked to a Core Person'); const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle(); if(me)throw me; if(!m)throw new Error('No active team membership found'); const {data:v,error:ve}=await db.from('vehicles').select('id,make,model,year,vin,logbook_number,notes,image_asset_id').eq('organisation_id',m.organisation_id).limit(1).maybeSingle(); if(ve)throw ve; if(!v)throw new Error('No vehicle found'); setVehicleId(v.id); setImageAssetId(v.image_asset_id||''); const {data:media}=await db.from('media_assets').select('id,name,asset_type,storage_path,mime_type').eq('organisation_id',m.organisation_id).order('created_at',{ascending:false});setAssets((media||[]).filter((x:any)=>!x.mime_type?.startsWith('video/')&&x.asset_type!=='Video')); const {data:r,error:re}=await db.from('raceiq_vehicle_profiles').select('vehicle_type,class_name,series_name').eq('vehicle_id',v.id).maybeSingle(); if(re)throw re; setForm({make:v.make||'',model:v.model||'',year:v.year?.toString()||'',vin:v.vin||'',logbook_number:v.logbook_number||'',notes:v.notes||'',vehicle_type:r?.vehicle_type||'',class_name:r?.class_name||'',series_name:r?.series_name||''}); const {data:members}=await db.from('organisation_members').select('id,person_id').eq('organisation_id',m.organisation_id).eq('membership_status','active'); for(const om of members||[]){const {data:roles}=await db.from('organisation_member_roles').select('*').eq('organisation_member_id',om.id); if((roles||[]).some((x:any)=>String(x.role_name||x.role||x.name||'').toLowerCase()==='driver')){const {data:l}=await db.from('person_licences').select('licence_number,status').eq('person_id',om.person_id).eq('status','active').limit(1).maybeSingle(); if(l?.licence_number){setRaceNumber(l.licence_number);break;}}}}catch(e:any){setError(e.message||'Unable to load vehicle')}finally{setLoading(false)}})()},[]);
 const change=(k:keyof Form,v:string)=>setForm(f=>({...f,[k]:v}));
 const save=async()=>{try{setSaving(true);setMessage('');setError('');const db=createClient(); const {error:ve}=await db.from('vehicles').update({make:form.make||null,model:form.model||null,year:form.year?Number(form.year):null,vin:form.vin||null,logbook_number:form.logbook_number||null,notes:form.notes||null,image_asset_id:imageAssetId||null,updated_at:new Date().toISOString()}).eq('id',vehicleId); if(ve)throw ve; const {error:re}=await db.from('raceiq_vehicle_profiles').update({vehicle_type:form.vehicle_type||null,class_name:form.class_name||null,series_name:form.series_name||null,updated_at:new Date().toISOString()}).eq('vehicle_id',vehicleId); if(re)throw re; setMessage('Vehicle details saved.');}catch(e:any){setError(e.message||'Unable to save vehicle')}finally{setSaving(false)}};
 const input=(label:string,key:keyof Form,type='text')=><label style={{display:'block',marginBottom:12}}><span className="muted" style={{display:'block',marginBottom:5}}>{label}</span><input type={type} value={form[key]} onChange={e=>change(key,e.target.value)} style={{width:'100%',maxWidth:320}}/></label>;
 if(loading)return <div className="card"><h3>Loading vehicle…</h3></div>;
 return <><div className="top"><div><div className="eyebrow">Garage / Vehicle / Edit</div><h1>Edit Vehicle Details</h1><div className="muted">Permanent vehicle and motorsport identity information</div></div></div>{error&&<p className="data-note">{error}</p>}<section className="grid"><div className="card"><div className="card-label">MOTORSPORT IDENTITY</div><h3>Competition</h3><p><span className="muted">Race Number</span><br/><strong>{raceNumber}</strong></p><p className="muted">Automatically sourced from the active driver's licence.</p>{input('Vehicle Type','vehicle_type')}{input('Class','class_name')}{input('Series','series_name')}</div><div className="card"><div className="card-label">CORE VEHICLE</div><h3>Vehicle Identity</h3>{input('Make / Manufacturer','make')}{input('Model','model')}{input('Year','year','number')}{input('VIN / Chassis Number','vin')}</div><div className="card"><div className="card-label">VEHICLE LOGBOOK</div><h3>Logbook</h3>{input('Logbook Number','logbook_number')}<p className="muted">Permanent logbook identifier for this vehicle.</p></div><div className="card"><div className="card-label">VEHICLE IMAGE</div><h3>Live Vehicle Background</h3><p className="muted">Choose an image from the Media Library.</p><select value={imageAssetId} onChange={e=>setImageAssetId(e.target.value)} style={{width:'100%'}}><option value="">No vehicle image selected</option>{assets.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{imageAssetId&&assets.find((a:any)=>a.id===imageAssetId)&&<img src={createClient().storage.from('media-library').getPublicUrl(assets.find((a:any)=>a.id===imageAssetId).storage_path).data.publicUrl} alt="Vehicle" style={{width:'100%',height:180,objectFit:'cover',marginTop:14,borderRadius:8}}/>}<p style={{marginTop:12}}><Link href="/media/assets/add">Add new asset</Link></p></div><div className="card"><div className="card-label">NOTES</div><h3>Vehicle Notes</h3><textarea value={form.notes} onChange={e=>change('notes',e.target.value)} rows={6} style={{width:'100%'}}/></div></section><div className="actions"><Link className="btn" href="/garage/vehicle">Cancel</Link><button className="btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save Vehicle'}</button>{message&&<span className="muted">{message}</span>}</div></>;
}
