'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

export default function Licences(){
 const id=useSearchParams().get('id');
 const [member,setMember]=useState<any>(null);const [person,setPerson]=useState<any>(null);const [licence,setLicence]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{if(!id)throw new Error('No team member selected');const db=createClient();const {data:om,error:oe}=await db.from('organisation_members').select('id,person_id,membership_status').eq('id',id).maybeSingle();if(oe)throw oe;if(!om)throw new Error('Team member not found');setMember(om);const {data:p,error:pe}=await db.from('core_people').select('*').eq('id',om.person_id).maybeSingle();if(pe)throw pe;setPerson(p);const {data:l,error:le}=await db.from('person_licences').select('*').eq('person_id',om.person_id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(le && !String(le.message||'').includes('person_licences'))throw le;setLicence(l||null)}catch(e:any){setError(e.message||'Unable to load licence')}finally{setLoading(false)}})()},[id]);
 const v=(...keys:string[])=>{for(const k of keys)if(licence?.[k]!==null&&licence?.[k]!==undefined&&licence?.[k]!=='')return licence[k];return 'Not recorded'};
 const name=person?.preferred_name||[person?.first_name,person?.last_name].filter(Boolean).join(' ')||'Driver';
 if(loading)return <div className="card"><h3>Loading driver licence…</h3></div>;
 return <><div className="top"><div><div className="eyebrow"><Link href={`/team/member?id=${id}`}>Member Profile</Link> / Driver Licence</div><h1>Driver Licence</h1><div className="muted">{name} · Shared Core People credential</div></div><div className="status">{String(v('status')).toUpperCase()}</div></div>{error&&<div className="card"><p className="data-note">{error}</p></div>}<section className="grid"><div className="card"><div className="card-label">LICENCE IDENTITY</div><h3>{v('licence_number','license_number','number')}</h3><p>Licence Type: {v('licence_type','license_type','type')}</p><p>Class: {v('licence_class','license_class','class')}</p><p>Issuing Authority: {v('issuing_authority','authority')}</p></div><div className="card"><div className="card-label">VALIDITY</div><h3>{v('status')}</h3><p>Issue Date: {v('issue_date','issued_at')}</p><p>Expiry Date: {v('expiry_date','expires_at')}</p></div><div className="card"><div className="card-label">RACE NUMBER</div><h3>{v('licence_number','license_number','number')}</h3><p className="muted">The driver's current licence number is used as their RaceIQ race number.</p></div><div className="card"><div className="card-label">DOCUMENT</div><h3>Licence Document</h3><p className="muted">Licence documents will be linked from the central Documents Library.</p></div></section>{!licence&&!error&&<div className="actions"><span className="muted">No driver licence record has been created for this Core Person yet.</span></div>}</>;
}
