'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import TeamPageHeader from '@/components/TeamPageHeader';

type EventRow={id:string;title:string;description:string|null;starts_at:string;ends_at:string|null;location:string|null;event_type:any};
export default function EventDetails(){
 const {id}=useParams<{id:string}>();const [event,setEvent]=useState<EventRow|null>(null),[crewCount,setCrewCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:e,error:ee}=await db.from('events').select('id,title,description,starts_at,ends_at,location,event_type').eq('id',id).maybeSingle();if(ee)throw ee;if(!e)throw new Error('Event not found');setEvent(e);const {count,error:ce}=await db.from('event_member_availability').select('id',{count:'exact',head:true}).eq('event_id',id);if(!ce)setCrewCount(count||0)}catch(e:any){setError(e.message||'Unable to load event')}finally{setLoading(false)}})()},[id]);
 const fmt=(s:string)=>new Intl.DateTimeFormat('en-AU',{day:'2-digit',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(s));
 if(loading)return <div className="card"><h3>Loading event…</h3></div>;if(error||!event)return <div className="card"><h3>Event unavailable</h3><p className="muted">{error}</p></div>;
 return <><TeamPageHeader module="RACE / EVENT" title={event.title} subtitle={`${event.location||'Location not recorded'} · ${fmt(event.starts_at)}`}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,margin:'0 0 16px'}}><div className="eyebrow"><Link href="/race/events">Race / Events</Link> / Event Details</div><div className="status">EVENT SET</div></div><section className="grid"><div className="card"><div className="card-label">EVENT OVERVIEW</div><h3>{event.title}</h3><p className="muted">Venue: {event.location||'Not recorded'}<br/>Starts: {fmt(event.starts_at)}<br/>{event.ends_at&&<>Ends: {fmt(event.ends_at)}<br/></>}Type: {String(event.event_type||'Not recorded')}</p>{event.description&&<p>{event.description}</p>}</div><div className="card"><div className="card-label">PIT ALLOCATION</div><h3>Not Assigned</h3><p className="muted">Record the team's pit location here so it remains prominent throughout the event.</p><button className="btn secondary" disabled>Add Pit Allocation</button></div><div className="card"><div className="card-label">SCHEDULE</div><h3>Event Schedule</h3><p className="muted">Add sessions and expected run times after event creation. Actual run time will later drive schedule variance.</p><button className="btn secondary" disabled>Add Schedule</button></div><div className="card"><div className="card-label">CREW</div><h3>{crewCount} Availability {crewCount===1?'Record':'Records'}</h3><p className="muted">Availability and event roles are linked from each team member's profile.</p><Link className="btn secondary" href="/team">View Team</Link></div><div className="card"><div className="card-label">VEHICLE</div><h3>Event Vehicle</h3><p className="muted">Select the vehicle attending this event and surface vehicle, maintenance and safety readiness.</p><Link className="btn secondary" href="/garage">Open Garage</Link></div><div className="card"><div className="card-label">PACKING</div><h3>Packing List</h3><p className="muted">Event-specific items with assignment and completion status.</p><button className="btn secondary" disabled>Open Packing</button></div><div className="card"><div className="card-label">TASKS</div><h3>Event Tasks</h3><p className="muted">Event tasks will use the shared RaceIQ Task Library and retain event context.</p><button className="btn secondary" disabled>Add Task</button></div><div className="card"><div className="card-label">DOCUMENTS</div><h3>Event Documents</h3><p className="muted">Entry forms, schedules and event documents will link into the central Documents Library.</p><button className="btn secondary" disabled>View Documents</button></div><div className="card"><div className="card-label">TRACK MODE</div><h3>Track Mode</h3><div className="status">Available when event is active</div><p className="muted">The focused race-day workspace will activate from this event.</p></div></section></>;
}
