'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';

export default function AddMediaAsset(){
 const router=useRouter();const [name,setName]=useState('');const [type,setType]=useState('Photo');const [notes,setNotes]=useState('');const [file,setFile]=useState<File|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const save=async()=>{try{if(!name.trim())throw new Error('Asset name is required');if(!file)throw new Error('Select a media file');if(file.type.startsWith('video/')&&!['video/mp4','video/webm'].includes(file.type))throw new Error('Unsupported video format. Please use MP4 (recommended) or WebM.');setSaving(true);setError('');const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const ext=file.name.includes('.')?file.name.split('.').pop()!.toLowerCase():'jpg';const path=`${m.organisation_id}/${crypto.randomUUID()}.${ext}`;const {error:se}=await db.storage.from('media-library').upload(path,file,{contentType:file.type||undefined,upsert:false});if(se)throw se;const {error:ie}=await db.from('media_assets').insert({organisation_id:m.organisation_id,name:name.trim(),asset_type:type,storage_path:path,mime_type:file.type||null,notes:notes.trim()||null,created_by:user.id});if(ie){await db.storage.from('media-library').remove([path]);throw ie;}router.push('/media');router.refresh();}catch(e:any){setError(e.message||'Unable to save media asset')}finally{setSaving(false)}};
 return <><header className="top"><div><div className="eyebrow"><Link href="/media">Media</Link> / Media Library / Add Asset</div><h1>Add Asset</h1><div className="muted">Add a reusable team image or branding asset to the central Media Library.</div></div></header>{error&&<p className="data-note">{error}</p>}<section className="grid"><div className="card"><div className="card-label">ASSET DETAILS</div><h3>Media Asset</h3><label><span className="muted" style={{display:'block',margin:'16px 0 6px'}}>Asset Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Team Primary Logo" style={{width:'100%'}}/></label><label><span className="muted" style={{display:'block',margin:'16px 0 6px'}}>Asset Type</span><select value={type} onChange={e=>setType(e.target.value)} style={{width:'100%'}}><option>Logo</option><option>Photo</option><option>Sponsor</option><option>Hero Image</option><option>Video</option><option>Other</option></select></label></div><div className="card"><div className="card-label">FILE</div><h3>Upload Asset</h3><label><span className="muted" style={{display:'block',margin:'16px 0 6px'}}>Media File</span><input type="file" accept="image/*,video/mp4,video/webm,.mp4,.webm" onChange={e=>setFile(e.target.files?.[0]||null)} style={{width:'100%'}}/></label><p className="muted" style={{marginTop:12}}>{file?file.name:'Select a photo, logo or video. MP4 (H.264) is recommended; WebM is also supported. WMV and other unsupported video formats must be converted before upload.'}</p></div><div className="card"><div className="card-label">NOTES</div><h3>Asset Notes</h3><textarea rows={6} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional usage or branding notes" style={{width:'100%'}}/></div><div className="card"><div className="card-label">CENTRAL LIBRARY</div><h3>Reusable Asset</h3><p className="muted">Once stored, this asset can be selected for the Team Profile, hero image, sponsor branding and other RaceIQ uses without uploading it again.</p></div></section><div style={{display:'flex',gap:10,marginTop:16}}><Link className="btn" href="/media">Cancel</Link><button className="btn" type="button" disabled={saving||!name.trim()||!file} onClick={save}>{saving?'Uploading…':'Add to Media Library'}</button></div></>;
}
