'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Item={id:string;item_name:string;category:string|null;default_assignee:string|null;is_active:boolean;sort_order:number};
type Member={id:string;name:string};
const CATEGORIES=['Safety','Race Gear','Tools','Equipment','Spares','Vehicle','Fuel & Fluids','Electrical','Pit Equipment','Transport','Documents','Food & Drinks','Personal','Other'];
export default function PackingListSettings(){
 const [orgId,setOrgId]=useState(''),[items,setItems]=useState<Item[]>([]),[members,setMembers]=useState<Member[]>([]),[name,setName]=useState(''),[category,setCategory]=useState(''),[assignee,setAssignee]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{load()},[]);
 async function load(){try{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');setOrgId(m.organisation_id);const {data:oms,error:ome}=await db.from('organisation_members').select('id,person_id').eq('organisation_id',m.organisation_id).eq('membership_status','active');if(ome)throw ome;const team:Member[]=[];for(const om of oms||[]){const {data:p}=await db.from('core_people').select('first_name,last_name,preferred_name').eq('id',om.person_id).maybeSingle();if(p)team.push({id:om.id,name:p.preferred_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||'Team Member'})}team.sort((a,b)=>a.name.localeCompare(b.name));setMembers(team);await loadItems(m.organisation_id)}catch(e:any){setError(e.message||'Unable to load packing list')}finally{setLoading(false)}}
 async function loadItems(oid=orgId){const db=createClient();const {data,error}=await db.from('packing_list_items').select('id,item_name,category,default_assignee,is_active,sort_order').eq('organisation_id',oid).order('sort_order').order('item_name');if(error)throw error;setItems(data||[])}
 async function addItem(){if(!name.trim()||!orgId)return;try{setSaving(true);setError('');const db=createClient();const {error}=await db.from('packing_list_items').insert({organisation_id:orgId,item_name:name.trim(),category:category||null,default_assignee:assignee||null,sort_order:items.length});if(error)throw error;setName('');setCategory('');setAssignee('');await loadItems()}catch(e:any){setError(e.message||'Unable to add item')}finally{setSaving(false)}}
 async function toggle(item:Item){try{const db=createClient();const {error}=await db.from('packing_list_items').update({is_active:!item.is_active,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)throw error;await loadItems()}catch(e:any){setError(e.message||'Unable to update item')}}
 async function remove(id:string){try{const db=createClient();const {error}=await db.from('packing_list_items').delete().eq('id',id);if(error)throw error;await loadItems()}catch(e:any){setError(e.message||'Unable to remove item')}}
 const assigneeName=(id:string|null)=>members.find(m=>m.id===id)?.name||'Unassigned';
 return <><header className="top"><div><div className="eyebrow">RaceIQ / Settings / Packing List</div><h1>Packing List</h1><div className="muted">Master event packing checklist for this team.</div></div></header>{error&&<p className="data-note">{error}</p>}<section className="grid"><div className="card" style={{gridColumn:'1 / -1'}}><div className="card-label">MASTER PACKING LIST</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><h3>{loading?'Loading…':`${items.filter(x=>x.is_active).length} Active Items`}</h3><Link className="btn secondary" href="/settings">Back to Settings</Link></div><div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr 1fr auto',gap:8,margin:'16px 0'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Item e.g. Helmet"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Select category</option>{CATEGORIES.map(c=><option key={c} value={c}>{c}</option>)}</select><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button className="btn" onClick={addItem} disabled={saving||!name.trim()}>{saving?'Adding…':'Add Item'}</button></div><div style={{maxHeight:420,overflowY:'auto'}}>{items.length?items.map(item=><div key={item.id} style={{display:'grid',gridTemplateColumns:'1.4fr 1fr 1fr .65fr auto',gap:12,alignItems:'center',padding:'11px 0',borderTop:'1px solid var(--line)',opacity:item.is_active?1:.55}}><strong>{item.item_name}</strong><span className="muted">{item.category||'Uncategorised'}</span><span className="muted">{assigneeName(item.default_assignee)}</span><button className="btn secondary" onClick={()=>toggle(item)}>{item.is_active?'Active':'Inactive'}</button><button className="btn secondary" onClick={()=>remove(item.id)}>Remove</button></div>):!loading&&<p className="muted">No packing items yet. Add the team's standard event items above.</p>}</div></div></section></>;
}
