'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Team={id:string;name:string;logo_asset_id:string|null;hero_asset_id:string|null};
type Asset={id:string;name:string;asset_type:string;storage_path:string};
export default function TeamProfileSettings(){
 const [team,setTeam]=useState<Team|null>(null);const [name,setName]=useState('');const [assets,setAssets]=useState<Asset[]>([]);const [logo,setLogo]=useState('');const [hero,setHero]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const url=(path:string)=>createClient().storage.from('media-library').getPublicUrl(path).data.publicUrl;
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const {data:o,error:oe}=await db.from('organisations').select('id,name,logo_asset_id,hero_asset_id').eq('id',m.organisation_id).single();if(oe)throw oe;const {data:media,error:mae}=await db.from('media_assets').select('id,name,asset_type,storage_path').eq('organisation_id',m.organisation_id).order('created_at',{ascending:false});if(mae)throw mae;setTeam(o);setName(o.name||'');setLogo(o.logo_asset_id||'');setHero(o.hero_asset_id||'');setAssets(media||[]);}catch(e:any){setError(e.message||'Unable to load team profile')}finally{setLoading(false)}})()},[]);
 const save=async()=>{try{if(!team)throw new Error('Team profile not loaded');if(!name.trim())throw new Error('Team name is required');setSaving(true);setError('');setMessage('');const db=createClient();const changes={name:name.trim(),logo_asset_id:logo||null,hero_asset_id:hero||null};const {data:updated,error:e}=await db.from('organisations').update(changes).eq('id',team.id).select('id,name,logo_asset_id,hero_asset_id').single();if(e)throw e;setTeam(updated);setMessage('Team profile saved.');}catch(e:any){setError(e.message||'Unable to save team profile')}finally{setSaving(false)}};
 const logos=assets.filter(a=>a.asset_type==='Logo'||a.asset_type==='Sponsor'||a.asset_type==='Other');const heroes=assets.filter(a=>a.asset_type==='Hero Image'||a.asset_type==='Photo'||a.asset_type==='Other');const selectedLogo=assets.find(a=>a.id===logo);const selectedHero=assets.find(a=>a.id===hero);
 if(loading)return <div className="card"><h3>Loading team profile…</h3></div>;
 return <><header className="top"><div><div className="eyebrow"><Link href="/settings">Settings</Link> / Team Profile</div><h1>Edit Team Profile</h1><div className="muted">Manage the team identity and branding used throughout RaceIQ.</div></div></header>{error&&<p className="data-note">{error}</p>}{message&&<p className="data-note">{message}</p>}<section className="grid"><div className="card"><div className="card-label">TEAM IDENTITY</div><h3>Team Details</h3><label><span className="muted" style={{display:'block',margin:'18px 0 6px'}}>Team Name</span><input value={name} onChange={e=>setName(e.target.value)} style={{width:'100%'}}/></label></div><div className="card"><div className="card-label">TEAM LOGO</div><h3>Logo</h3><p className="muted">Select the team's primary logo from the Media Library.</p><select value={logo} onChange={e=>setLogo(e.target.value)} style={{width:'100%'}}><option value="">No logo selected</option>{logos.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{selectedLogo&&<img src={url(selectedLogo.storage_path)} alt={selectedLogo.name} style={{width:'100%',height:150,objectFit:'contain',marginTop:14,borderRadius:8}}/>}<p style={{marginTop:12}}><Link href="/media/assets/add">Add new asset</Link></p></div><div className="card"><div className="card-label">HERO IMAGE</div><h3>Main Team Image</h3><p className="muted">Choose the main hero image used on the team and Home experience.</p><select value={hero} onChange={e=>setHero(e.target.value)} style={{width:'100%'}}><option value="">No hero image selected</option>{heroes.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{selectedHero&&<img src={url(selectedHero.storage_path)} alt={selectedHero.name} style={{width:'100%',height:190,objectFit:'cover',marginTop:14,borderRadius:8}}/>}<p style={{marginTop:12}}><Link href="/media/assets/add">Add new asset</Link></p></div></section><div style={{display:'flex',gap:10,marginTop:16}}><Link className="btn" href="/settings">Cancel</Link><button className="btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save Team Profile'}</button></div></>;
}
