'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Team={id:string;name:string};
export default function TeamProfileSettings(){
 const [team,setTeam]=useState<Team|null>(null);const [name,setName]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const {data:o,error:oe}=await db.from('organisations').select('id,name').eq('id',m.organisation_id).single();if(oe)throw oe;setTeam(o);setName(o.name||'');}catch(e:any){setError(e.message||'Unable to load team profile')}finally{setLoading(false)}})()},[]);
 const save=async()=>{try{if(!team)throw new Error('Team profile not loaded');if(!name.trim())throw new Error('Team name is required');setSaving(true);setError('');setMessage('');const db=createClient();const {error:e}=await db.from('organisations').update({name:name.trim()}).eq('id',team.id);if(e)throw e;setTeam({...team,name:name.trim()});setMessage('Team profile saved.');}catch(e:any){setError(e.message||'Unable to save team profile')}finally{setSaving(false)}};
 if(loading)return <div className="card"><h3>Loading team profile…</h3></div>;
 return <><header className="top"><div><div className="eyebrow"><Link href="/settings">Settings</Link> / Team Profile</div><h1>Edit Team Profile</h1><div className="muted">Manage the team identity and the branding used throughout RaceIQ.</div></div></header>{error&&<p className="data-note">{error}</p>}{message&&<p className="data-note">{message}</p>}<section className="grid"><div className="card"><div className="card-label">TEAM IDENTITY</div><h3>Team Details</h3><label><span className="muted" style={{display:'block',margin:'18px 0 6px'}}>Team Name</span><input value={name} onChange={e=>setName(e.target.value)} style={{width:'100%'}} /></label></div><div className="card"><div className="card-label">TEAM LOGO</div><h3>Logo</h3><p className="muted">Select the team's primary logo from the Media Library.</p><button className="btn" type="button" disabled>Select from Media Library</button><p className="muted" style={{marginTop:12}}>Media selection will be connected to the central Media Library.</p></div><div className="card"><div className="card-label">HERO IMAGE</div><h3>Main Team Image</h3><p className="muted">Choose the main hero image used on the team and Home experience.</p><button className="btn" type="button" disabled>Select from Media Library</button><p className="muted" style={{marginTop:12}}>Team branding assets remain centrally managed in Media.</p></div></section><div style={{display:'flex',gap:10,marginTop:16}}><Link className="btn" href="/settings">Cancel</Link><button className="btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save Team Profile'}</button></div></>;
}
