'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Member={id:string;person_id:string;membership_status:string;display_name:string;roles:string[]};
export default function Member(){
 const params=useSearchParams(); const memberId=params.get('id'); const [m,setM]=useState<Member|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{if(!memberId)throw new Error('No team member selected');const db=createClient();const {data:om,error:oe}=await db.from('organisation_members').select('id,person_id,membership_status').eq('id',memberId).maybeSingle();if(oe)throw oe;if(!om)throw new Error('Team member not found');let display='Team Member';const {data:p}=await db.from('core_people').select('*').eq('id',om.person_id).maybeSingle();if(p)display=p.display_name||p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||p.name||display;const {data:rr}=await db.from('organisation_member_roles').select('*').eq('organisation_member_id',om.id);const roles=(rr||[]).map((r:any)=>r.role_name||r.role||r.name).filter(Boolean);setM({...om,display_name:display,roles});}catch(e:any){setError(e.message||'Unable to load member')}finally{setLoading(false)}})()},[memberId]);
 if(loading)return <div className="card"><h3>Loading member profile…</h3></div>;if(error)return <><div className="card"><h3>Member unavailable</h3><p className="muted">{error}</p></div><div className="actions"><Link className="btn" href="/team">Back to Team</Link></div></>;
 const driver=m?.roles.some(r=>String(r).toLowerCase().includes('driver'));
 return <><div className="top"><div><div className="eyebrow">Team / Member Profile</div><h1>{m?.display_name}</h1><div className="muted">Shared Core People identity · {m?.roles.length?m.roles.join(' · '):'Team Member'}</div></div><div className="status">{m?.membership_status.toUpperCase()}</div></div><section className="grid"><div className="card"><div className="card-label">PROFILE</div><h3>Personal Details</h3><p className="muted">Core identity, contact details and team information.</p></div><div className="card"><div className="card-label">ROLES</div><h3>Team Roles</h3><p className="muted">{m?.roles.length?m.roles.join(' · '):'No roles assigned'}</p></div><div className="card"><div className="card-label">LICENCES & CREDENTIALS</div><h3>{driver?'Driver Licence':'Credentials'}</h3><p className="muted">{driver?'Driver licence number becomes the race number for this driver.':'Licences, qualifications and credentials.'}</p></div>{driver&&<div className="card"><div className="card-label">SAFETY LOGBOOK</div><h3>Driver Safety Equipment</h3><p className="muted">Helmet · Race suit · Gloves · Shoes · Restraints and compliance documents.</p></div>}<div className="card"><div className="card-label">AVAILABILITY</div><h3>Event Availability</h3><p className="muted">Availability and event assignments.</p></div><div className="card"><div className="card-label">TASKS</div><h3>Assigned Tasks</h3><p className="muted">Tasks assigned to this member from the central Task Library.</p><button className="btn">Assign Task</button></div><div className="card"><div className="card-label">DOCUMENTS</div><h3>Member Documents</h3><p className="muted">Personal documents, licences, medicals and credentials linked from the central Documents Library.</p></div><div className="card"><div className="card-label">NOTES</div><h3>Member Notes</h3><p className="muted">Team administration notes for this member.</p></div></section><div className="actions"><button className="btn">Edit Member</button><Link className="btn" href="/team">Back to Team</Link></div></>;
}
