'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Vehicle={id:string;logbook_number?:string|null;vin?:string|null;make?:string|null;model?:string|null;year?:number|null;status?:string|null;notes?:string|null};
type RaceProfile={vehicle_type?:string|null;class_name?:string|null;series_name?:string|null};
export default function LiveVehicleDetails(){
 const [v,setV]=useState<Vehicle|null>(null),[race,setRace]=useState<RaceProfile|null>(null),[raceNumber,setRaceNumber]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const {data:vehicle,error:ve}=await db.from('vehicles').select('id,logbook_number,vin,make,model,year,status,notes').eq('organisation_id',m.organisation_id).limit(1).maybeSingle();if(ve)throw ve;setV(vehicle);if(vehicle){const {data:rp,error:rpe}=await db.from('raceiq_vehicle_profiles').select('vehicle_type,class_name,series_name').eq('vehicle_id',vehicle.id).maybeSingle();if(rpe)throw rpe;setRace(rp)}const {data:members}=await db.from('organisation_members').select('id,person_id').eq('organisation_id',m.organisation_id).eq('membership_status','active');for(const om of members||[]){const {data:roles}=await db.from('organisation_member_roles').select('*').eq('organisation_member_id',om.id);if((roles||[]).some((x:any)=>String(x.role_name||x.role||x.name||'').toLowerCase()==='driver')){const {data:l}=await db.from('person_licences').select('licence_number,status').eq('person_id',om.person_id).eq('status','active').limit(1).maybeSingle();if(l?.licence_number){setRaceNumber(l.licence_number);break}}}}catch(e:any){setError(e.message||'Unable to load vehicle')}finally{setLoading(false)}})()},[]);
 const base=v?`${v.year||''} ${v.make||''} ${v.model||''}`.replace(/\s+/g,' ').trim():'Vehicle',title=`${base}${raceNumber?` #${raceNumber}`:''}`;
 if(loading)return <div className="card"><h3>Loading vehicle…</h3></div>;if(error)return <div className="card"><h3>Vehicle unavailable</h3><p className="muted">{error}</p></div>;
 return <><div className="top"><div><div className="eyebrow">Garage / Vehicle</div><h1>{title}</h1><div className="muted">{race?.vehicle_type||'Vehicle'}{race?.class_name?` · ${race.class_name}`:''}{race?.series_name?` · ${race.series_name}`:''}</div></div><div className="status">{(v?.status||'active').toUpperCase()}</div></div><section className="grid"><Link className="card card-link" href="/garage/vehicle/edit"><div className="card-label">MOTORSPORT IDENTITY</div><h3>{v?.make} {v?.model}{raceNumber?` #${raceNumber}`:''}</h3><p className="muted">Race Number: {raceNumber||'Not recorded'}<br/>Type: {race?.vehicle_type||'Not recorded'}<br/>Class: {race?.class_name||'Not recorded'}<br/>Series: {race?.series_name||'Not recorded'}</p></Link><Link className="card card-link" href="/garage/vehicle/setup"><div className="card-label">CURRENT SETUP</div><h3>Setup</h3><p className="muted">User-configurable race setup fields and current values.</p></Link><Link className="card card-link" href="/garage/vehicle/engineering"><div className="card-label">ENGINEERING</div><h3>Engineering</h3><p className="muted">Maintenance, component life, run counters and engineering history.</p></Link><div className="card"><div className="card-label">VEHICLE LOGBOOK</div><h3>Logbook {v?.logbook_number||'Not recorded'}</h3><p className="muted">Permanent logbook identifier for the current vehicle.</p></div><div className="card"><div className="card-label">RUN HISTORY</div><h3>Run History</h3><p className="muted">RaceIQ event and run history for this vehicle.</p></div><div className="card"><div className="card-label">CORE VEHICLE</div><h3>Vehicle Identity</h3><p className="muted">Year: {v?.year||'Not recorded'}<br/>VIN / Chassis: {v?.vin||'Not recorded'}<br/>Logbook: {v?.logbook_number||'Not recorded'}</p></div></section>{v?.notes&&<p className="data-note">Vehicle notes: {v.notes}</p>}</>;
}
