'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Member={id:string;person_id:string;membership_status:string;display_name:string;roles:string[]};
export default function LiveTeamMembers(){
 const [members,setMembers]=useState<Member[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:mine,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!mine)throw new Error('No active team membership found');const {data:rows,error:re}=await db.from('organisation_members').select('id,person_id,membership_status').eq('organisation_id',mine.organisation_id).order('created_at');if(re)throw re;const enriched=await Promise.all((rows||[]).map(async(row:any)=>{let display='Team Member';const {data:p}=await db.from('core_people').select('*').eq('id',row.person_id).maybeSingle();if(p){display=p.display_name||p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||p.name||display}const {data:rr}=await db.from('organisation_member_roles').select('*').eq('organisation_member_id',row.id);const roles=(rr||[]).map((r:any)=>r.role_name||r.role||r.name).filter(Boolean);return {...row,display_name:display,roles};}));setMembers(enriched)}catch(e:any){setError(e.message||'Unable to load team members')}finally{setLoading(false)}})()},[]);
 if(loading)return <div className="card"><h3>Loading team members…</h3></div>;
 return <div className="card"><div className="card-label">TEAM MEMBERS</div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16}}><h3 style={{margin:0}}>{members.length} Team Member{members.length===1?'':'s'}</h3><Link className="btn" href="/team/add">Add Member</Link></div>{error&&<p className="data-note">{error}</p>} {!error&&<div style={{marginTop:14}}>{members.map(m=><Link key={m.id} href={`/team/member?id=${m.id}`} className="card-link" style={{display:'grid',gridTemplateColumns:'2fr 2fr 1fr',gap:16,padding:'16px 12px',borderTop:'1px solid rgba(255,255,255,.09)',textDecoration:'none'}}><strong>{m.display_name}</strong><span className="muted">{m.roles.length?m.roles.join(' · '):'Team Member'}</span><span className="status">{m.membership_status.toUpperCase()}</span></Link>)}{members.length===0&&<p className="muted">No team members found.</p>}</div>}</div>;
}
