'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type State={org:string;members:number;vehicles:number;nextEvent:string;venue:string;eventDate:string;readiness:string;loading:boolean;error?:string};
export default function LiveHome(){
 const [s,setS]=useState<State>({org:"Scott's Aussie Car Racing",members:0,vehicles:0,nextEvent:'No event scheduled',venue:'',eventDate:'',readiness:'PENDING',loading:true});
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:userError}=await db.auth.getUser();if(userError)throw userError;if(!user)throw new Error('Please sign in to load RaceIQ data');const {data:authLink,error:authError}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(authError)throw authError;if(!authLink)throw new Error('Your login is not linked to a Core Person');const {data:membership,error:membershipError}=await db.from('organisation_members').select('organisation_id').eq('person_id',authLink.person_id).eq('membership_status','active').limit(1).maybeSingle();if(membershipError)throw membershipError;if(!membership)throw new Error('No active team membership found');const {data:o,error:orgError}=await db.from('organisations').select('id,name').eq('id',membership.organisation_id).single();if(orgError)throw orgError;const now=new Date().toISOString();const [{count:members,error:membersError},{count:vehicles,error:vehiclesError},{data:event,error:eventError}]=await Promise.all([db.from('organisation_members').select('*',{count:'exact',head:true}).eq('organisation_id',o.id).eq('membership_status','active'),db.from('vehicles').select('*',{count:'exact',head:true}).eq('organisation_id',o.id),db.from('events').select('id,title,location,starts_at,ends_at').eq('organisation_id',o.id).or(`ends_at.gte.${now},and(ends_at.is.null,starts_at.gte.${now})`).order('starts_at').limit(1).maybeSingle()]);if(membersError)throw membersError;if(vehiclesError)throw vehiclesError;if(eventError)throw eventError;const eventDate=event?.starts_at?new Date(event.starts_at).toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'}):'';setS({org:o.name,members:members||0,vehicles:vehicles||0,nextEvent:event?.title||'No event scheduled',venue:event?.location||'',eventDate,readiness:event?'EVENT SET':'PENDING',loading:false});}catch(e:any){setS(x=>({...x,loading:false,error:e.message||'Unable to load live data'}))}})()},[]);
 return <><div className="live-strip"><span className="card-label">LIVE SUPABASE</span><strong>{s.loading?'Connecting…':s.error?'Connection requires login/environment':s.org}</strong></div><section className="dashboard-grid"><Link className="card card-link" href="/race/events"><div className="card-label">NEXT EVENT</div><h3>{s.nextEvent}</h3><div className="metric">{s.readiness}</div><p className="muted">{s.eventDate}{s.eventDate&&s.venue?' · ':''}{s.venue||(!s.eventDate?'Event readiness will appear here.':'')}</p></Link><Link className="card card-link" href="/garage"><div className="card-label">VEHICLES</div><h3>Garage</h3><div className="metric">{s.loading?'—':s.vehicles}</div><p className="muted">Active Core vehicle records.</p></Link><Link className="card card-link" href="/team"><div className="card-label">TEAM</div><h3>People</h3><div className="metric">{s.loading?'—':s.members}</div><p className="muted">People linked to this team.</p></Link></section>{s.error&&<p className="data-note">Live data: {s.error}</p>}</>;
}
