'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Vehicle={id:string;registration_number?:string|null;vin?:string|null;make?:string|null;model?:string|null;year?:number|null;license_region?:string|null;status?:string|null;notes?:string|null};
type RaceProfile={competition_number?:string|null;vehicle_type?:string|null;class_name?:string|null;series_name?:string|null};
type Logbook={id:string;title:string;description?:string|null;started_at?:string|null;ended_at?:string|null};
export default function LiveVehicleDetails(){
 const [v,setV]=useState<Vehicle|null>(null),[race,setRace]=useState<RaceProfile|null>(null),[logbook,setLogbook]=useState<Logbook|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const {data:vehicle,error:ve}=await db.from('vehicles').select('id,registration_number,vin,make,model,year,license_region,status,notes').eq('organisation_id',m.organisation_id).limit(1).maybeSingle();if(ve)throw ve;setV(vehicle);if(vehicle){const [{data:rp,error:rpe},{data:lb,error:lbe}]=await Promise.all([db.from('raceiq_vehicle_profiles').select('competition_number,vehicle_type,class_name,series_name').eq('vehicle_id',vehicle.id).maybeSingle(),db.from('vehicle_logbooks').select('id,title,description,started_at,ended_at').eq('vehicle_id',vehicle.id).order('started_at',{ascending:false}).limit(1).maybeSingle()]);if(rpe)throw rpe;if(lbe)throw lbe;setRace(rp);setLogbook(lb)}}catch(e:any){setError(e.message||'Unable to load vehicle')}finally{setLoading(false)}})()},[]);
 const base=v?`${v.year||''} ${v.make||''} ${v.model||''}`.replace(/\s+/g,' ').trim():'Vehicle',title=`${base}${race?.competition_number?` #${race.competition_number}`:''}`;
 if(loading)return <div className="card"><h3>Loading vehicle…</h3></div>;if(error)return <div className="card"><h3>Vehicle unavailable</h3><p className="muted">{error}</p></div>;
 return <><div className="top"><div><div className="eyebrow">Garage / Vehicle</div><h1>{title}</h1><div className="muted">{race?.vehicle_type||'Vehicle'}{race?.class_name?` · ${race.class_name}`:''}{race?.series_name?` · ${race.series_name}`:''}</div></div><div className="status">{(v?.status||'active').toUpperCase()}</div></div><section className="grid"><div className="card"><div className="card-label">MOTORSPORT IDENTITY</div><h3>{v?.make} {v?.model}{race?.competition_number?` #${race.competition_number}`:''}</h3><p className="muted">Type: {race?.vehicle_type||'Not recorded'}<br/>Class: {race?.class_name||'Not recorded'}<br/>Series: {race?.series_name||'Not recorded'}</p><Link className="btn" href="/garage/vehicle/edit">Edit Vehicle</Link></div><div className="card"><div className="card-label">CURRENT SETUP</div><h3>Setup</h3><p className="muted">User-configurable race setup fields and current values.</p><Link className="btn" href="/garage/vehicle/setup">Open Setup</Link></div><div className="card"><div className="card-label">ENGINEERING</div><h3>Engineering</h3><p className="muted">Maintenance, component life, run counters and engineering history.</p></div><div className="card"><div className="card-label">DOCUMENTS</div><h3>{logbook?.title||'Vehicle Documents'}</h3><p className="muted">{logbook?`${logbook.ended_at?'Closed':'Active'} vehicle logbook${logbook.description?` · ${logbook.description}`:''}`:'No vehicle logbook recorded.'}</p></div><div className="card"><div className="card-label">RUN HISTORY</div><h3>Run History</h3><p className="muted">RaceIQ event and run history for this vehicle.</p></div><div className="card"><div className="card-label">CORE VEHICLE</div><h3>Vehicle Identity</h3><p className="muted">Year: {v?.year||'Not recorded'}<br/>VIN / Chassis: {v?.vin||'Not recorded'}<br/>Registration: {v?.registration_number||'Not recorded'}{v?.license_region?` · ${v.license_region}`:''}</p></div></section>{v?.notes&&<p className="data-note">Vehicle notes: {v.notes}</p>}</>;
}
