'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
type Task={id:string;task_name:string;category:string|null;is_active:boolean;sort_order:number};
const CATEGORIES=['Race Preparation','Vehicle','Maintenance','Safety','Crew','Transport','Packing','Administration','Media','Other'];
export default function TaskLibrary(){
 const [orgId,setOrgId]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[name,setName]=useState(''),[category,setCategory]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{load()},[]);
 async function load(){try{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('Please sign in');const {data:a}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(!a)throw new Error('Login is not linked to a Core Person');const {data:m}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(!m)throw new Error('No active team membership found');setOrgId(m.organisation_id);await reload(db,m.organisation_id)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function reload(db:any=createClient(),oid=orgId){const {data,error}=await db.from('task_library_items').select('*').eq('organisation_id',oid).order('sort_order').order('task_name');if(error)throw error;setTasks(data||[])}
 async function add(){if(!name.trim())return;try{const db=createClient();const {error}=await db.from('task_library_items').insert({organisation_id:orgId,task_name:name.trim(),category:category||null,sort_order:tasks.length});if(error)throw error;setName('');setCategory('');await reload(db)}catch(e:any){setError(e.message)}}
 async function toggle(t:Task){const db=createClient();const {error}=await db.from('task_library_items').update({is_active:!t.is_active,updated_at:new Date().toISOString()}).eq('id',t.id);if(error)setError(error.message);else await reload(db)}
 async function remove(id:string){const db=createClient();const {error}=await db.from('task_library_items').delete().eq('id',id);if(error)setError(error.message);else await reload(db)}
 return <><header className="top"><div><div className="eyebrow">RaceIQ / Settings / Task Library</div><h1>Task Library</h1><div className="muted">Reusable tasks available throughout RaceIQ.</div></div></header>{error&&<p className="data-note">{error}</p>}<section className="grid"><div className="card" style={{gridColumn:'1 / -1'}}><div className="card-label">CENTRAL TASK LIBRARY</div><div style={{display:'flex',justifyContent:'space-between'}}><h3>{loading?'Loading…':tasks.filter(x=>x.is_active).length+' Active Tasks'}</h3><Link className="btn secondary" href="/settings">Back to Settings</Link></div><div style={{display:'grid',gridTemplateColumns:'1.6fr 1fr auto',gap:8,margin:'16px 0'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Task e.g. Charge batteries"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Select category</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><button className="btn" onClick={add}>Add Task</button></div><div style={{maxHeight:420,overflowY:'auto'}}>{tasks.map(t=><div key={t.id} style={{display:'grid',gridTemplateColumns:'1.6fr 1fr .6fr auto',gap:12,alignItems:'center',padding:'11px 0',borderTop:'1px solid var(--line)',opacity:t.is_active?1:.55}}><strong>{t.task_name}</strong><span className="muted">{t.category||'Uncategorised'}</span><button className="btn secondary" onClick={()=>toggle(t)}>{t.is_active?'Active':'Inactive'}</button><button className="btn secondary" onClick={()=>remove(t.id)}>Remove</button></div>)}</div></div></section></>;
}