'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

export default function AddEvent(){
 const router=useRouter();const [orgId,setOrgId]=useState(''),[createdBy,setCreatedBy]=useState(''),[title,setTitle]=useState(''),[location,setLocation]=useState(''),[startsAt,setStartsAt]=useState(''),[endsAt,setEndsAt]=useState(''),[description,setDescription]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');setCreatedBy(user.id);const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');setOrgId(m.organisation_id)}catch(e:any){setError(e.message||'Unable to prepare event')}finally{setLoading(false)}})()},[]);
 const save=async()=>{try{if(!title.trim())throw new Error('Event name is required');if(!startsAt)throw new Error('Start date and time are required');setSaving(true);setError('');const db=createClient();const payload:any={organisation_id:orgId,title:title.trim(),location:location.trim()||null,starts_at:new Date(startsAt).toISOString(),ends_at:endsAt?new Date(endsAt).toISOString():null,description:description.trim()||null,created_by:createdBy};const {data,error:e}=await db.from('events').insert(payload).select('id').single();if(e)throw e;router.push(`/race/events/${data.id}`)}catch(e:any){setError(e.message||'Unable to create event')}finally{setSaving(false)}};
 if(loading)return <div className="card"><h3>Preparing event…</h3></div>;
 return <><div className="top"><div><div className="eyebrow">Race / Events / Add Event</div><h1>Add Event</h1><div className="muted">Create the event now. Schedule and detailed event operations can be added later.</div></div></div>{error&&<p className="data-note">{error}</p>}<section className="grid"><div className="card"><div className="card-label">EVENT DETAILS</div><h3>Event</h3><label><span className="muted">Event Name</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Willowbank Junior Drag Racing" style={{width:'100%',margin:'6px 0 14px'}}/></label><label><span className="muted">Venue / Location</span><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Willowbank Raceway" style={{width:'100%',marginTop:6}}/></label></div><div className="card"><div className="card-label">DATE & TIME</div><h3>Event Timing</h3><label><span className="muted">Starts</span><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} style={{width:'100%',margin:'6px 0 14px'}}/></label><label><span className="muted">Ends</span><input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} style={{width:'100%',marginTop:6}}/></label><p className="muted">The detailed race schedule is added later.</p></div><div className="card"><div className="card-label">EVENT NOTES</div><h3>Description</h3><textarea rows={7} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional event information" style={{width:'100%'}}/></div><div className="card"><div className="card-label">EVENT OPERATIONS</div><h3>Added After Creation</h3><p className="muted">Schedule · Pit Allocation · Crew Availability · Packing · Tasks · Documents · Track Mode</p></div></section><div className="actions"><Link className="btn" href="/race/events">Cancel</Link><button className="btn" onClick={save} disabled={saving||!orgId}>{saving?'Creating…':'Create Event'}</button></div></>;
}
