'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type EventRow={id:string;event_type:any;title:string;description:string|null;starts_at:string;ends_at:string|null;location:string|null};
export default function EventsPage(){
 const [events,setEvents]=useState<EventRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const {data:ev,error:ee}=await db.from('events').select('id,event_type,title,description,starts_at,ends_at,location').eq('organisation_id',m.organisation_id).order('starts_at',{ascending:true});if(ee)throw ee;setEvents(ev||[])}catch(e:any){setError(e.message||'Unable to load events')}finally{setLoading(false)}})()},[]);
 const fmt=(s:string)=>new Intl.DateTimeFormat('en-AU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s));
 const now=Date.now(),upcoming=events.filter(e=>new Date(e.ends_at||e.starts_at).getTime()>=now),past=events.filter(e=>new Date(e.ends_at||e.starts_at).getTime()<now).reverse();
 if(loading)return <div className="card"><h3>Loading events…</h3></div>;
 return <><div className="top"><div><div className="eyebrow">Race / Events</div><h1>Events</h1><div className="muted">Race events, venues and event operations.</div></div></div>{error&&<p className="data-note">{error}</p>}<section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><div><div className="card-label">UPCOMING EVENTS</div><h3>{upcoming.length} Upcoming {upcoming.length===1?'Event':'Events'}</h3></div><Link className="btn" href="/race/events/add">Add Event</Link></div>{upcoming.length===0?<p className="muted">No upcoming events. Add an event to begin planning.</p>:<div style={{marginTop:14}}>{upcoming.map(e=><Link key={e.id} href={`/race/events/${e.id}`} className="card-link" style={{display:'grid',gridTemplateColumns:'1.5fr .8fr .8fr',gap:18,padding:'18px 10px',borderTop:'1px solid #303833'}}><div><strong>{e.title}</strong><div className="muted">{e.location||'Location not recorded'}</div></div><div><div className="card-label">DATE</div><div>{fmt(e.starts_at)}{e.ends_at?` – ${fmt(e.ends_at)}`:''}</div></div><div><div className="card-label">TYPE</div><div>{String(e.event_type||'Event')}</div></div></Link>)}</div>}</section>{past.length>0&&<section className="card" style={{marginTop:16}}><div className="card-label">PAST EVENTS</div><h3>{past.length} Past {past.length===1?'Event':'Events'}</h3>{past.map(e=><Link key={e.id} href={`/race/events/${e.id}`} className="card-link" style={{display:'grid',gridTemplateColumns:'1.5fr .8fr',gap:18,padding:'16px 10px',borderTop:'1px solid #303833'}}><div><strong>{e.title}</strong><div className="muted">{e.location||'Location not recorded'}</div></div><div>{fmt(e.starts_at)}</div></Link>)}</section>}</>;
}
