'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
type Doc={id:string;document_name:string;category:string|null;file_name:string|null;storage_path:string|null;created_at:string;event_id:string|null;organisation_member_id:string|null;vehicle_id:string|null};
export default function DocumentsLibrary(){
 const [docs,setDocs]=useState<Doc[]>([]),[filter,setFilter]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{load()},[]);
 async function load(){try{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('Please sign in');const {data:a}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(!a)throw new Error('Login is not linked to a Core Person');const {data:m}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(!m)throw new Error('No active team membership found');const {data,error}=await db.from('documents').select('id,document_name,category,file_name,storage_path,created_at,event_id,organisation_member_id,vehicle_id').eq('organisation_id',m.organisation_id).order('created_at',{ascending:false});if(error)throw error;setDocs(data||[])}catch(e:any){setError(e.message||'Unable to load documents')}finally{setLoading(false)}}
 async function openDoc(d:Doc){if(!d.storage_path)return;try{const db=createClient();const {data,error}=await db.storage.from('documents').createSignedUrl(d.storage_path,60);if(error)throw error;if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}catch(e:any){setError(e.message||'Unable to open document')}}
 const shown=docs.filter(d=>!filter||d.document_name.toLowerCase().includes(filter.toLowerCase())||(d.category||'').toLowerCase().includes(filter.toLowerCase())||(d.file_name||'').toLowerCase().includes(filter.toLowerCase()));
 const context=(d:Doc)=>d.event_id?'Event':d.organisation_member_id?'Member':d.vehicle_id?'Vehicle':'Team';
 return <><header className="top"><div><div className="eyebrow">RaceIQ / Documents</div><h1>Documents Library</h1><div className="muted">One central library for team, event, member and vehicle documents.</div></div></header>{error&&<p className="data-note">{error}</p>}<section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div className="card-label">CENTRAL LIBRARY</div><h3>All Documents</h3></div><div className="status">{shown.length} Documents</div></div><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search documents or categories…" style={{width:'100%',margin:'12px 0'}}/><div style={{maxHeight:520,overflowY:'auto'}}>{loading?<p className="muted">Loading documents…</p>:shown.length?shown.map(d=><div key={d.id} style={{display:'grid',gridTemplateColumns:'1.6fr .8fr .6fr .6fr',gap:12,alignItems:'center',padding:'11px 4px',borderBottom:'1px solid var(--line)'}}><button onClick={()=>openDoc(d)} disabled={!d.storage_path} style={{background:'none',border:0,padding:0,textAlign:'left',color:'inherit',cursor:d.storage_path?'pointer':'default'}}><strong>{d.document_name}</strong><small className="muted" style={{display:'block'}}>{d.file_name||'Record only'}</small></button><span>{d.category||'Uncategorised'}</span><span className="status">{context(d)}</span><small className="muted">{new Date(d.created_at).toLocaleDateString('en-AU')}</small></div>):<p className="muted">No documents in the library yet.</p>}</div></section><div style={{marginTop:16}}><Link href="/settings" className="btn secondary">Back to Settings</Link></div></>;
}