'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type EventRow={id:string;title:string;event_type:any;starts_at:string;ends_at:string|null;location:string|null};
type Availability={id?:string;event_id:string;availability_status?:string|null;event_role?:string|null;notes?:string|null};

export default function EventAvailability(){
 const params=useSearchParams(); const memberId=params.get('id');
 const [name,setName]=useState('Team Member'); const [personId,setPersonId]=useState(''); const [events,setEvents]=useState<EventRow[]>([]); const [availability,setAvailability]=useState<Record<string,Availability>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState('');
 useEffect(()=>{(async()=>{try{if(!memberId)throw new Error('No team member selected'); const db=createClient(); const {data:m,error:me}=await db.from('organisation_members').select('id,person_id,organisation_id').eq('id',memberId).maybeSingle(); if(me)throw me;if(!m)throw new Error('Team member not found'); setPersonId(m.person_id); const {data:p}=await db.from('core_people').select('first_name,last_name,preferred_name').eq('id',m.person_id).maybeSingle(); if(p)setName(p.preferred_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||'Team Member'); const {data:ev,error:ee}=await db.from('events').select('id,title,event_type,starts_at,ends_at,location').eq('organisation_id',m.organisation_id).gte('ends_at',new Date().toISOString()).order('starts_at',{ascending:true}); if(ee)throw ee; setEvents(ev||[]); const {data:av,error:ae}=await db.from('event_member_availability').select('*').eq('person_id',m.person_id); if(ae)throw ae; const map:Record<string,Availability>={}; for(const x of av||[])map[x.event_id]=x; setAvailability(map);}catch(e:any){setError(e.message||'Unable to load event availability')}finally{setLoading(false)}})()},[memberId]);
 const updateLocal=(eventId:string,key:'availability_status'|'event_role'|'notes',value:string)=>setAvailability(a=>({...a,[eventId]:{...(a[eventId]||{event_id:eventId}),[key]:value}}));
 const save=async(eventId:string)=>{try{setSaving(eventId);setError('');const db=createClient();const row=availability[eventId]||{event_id:eventId};const payload:any={event_id:eventId,person_id:personId,availability_status:row.availability_status||'not_set',event_role:row.event_role||null,notes:row.notes||null};const {data:existing}=await db.from('event_member_availability').select('id').eq('event_id',eventId).eq('person_id',personId).maybeSingle();let q;if(existing?.id)q=await db.from('event_member_availability').update(payload).eq('id',existing.id).select().single();else q=await db.from('event_member_availability').insert(payload).select().single();if(q.error)throw q.error;setAvailability(a=>({...a,[eventId]:q.data}));}catch(e:any){setError(e.message||'Unable to save availability')}finally{setSaving('')}};
 const fmt=(s:string)=>new Intl.DateTimeFormat('en-AU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s));
 if(loading)return <div className="card"><h3>Loading event availability…</h3></div>;
 return <><div className="top"><div><div className="eyebrow"><Link href={`/team/member?id=${memberId}`}>Member Profile</Link> / Event Availability</div><h1>Event Availability</h1><div className="muted">{name} · upcoming events and assignments</div></div></div>{error&&<p className="data-note">{error}</p>}<div className="card"><div className="card-label">UPCOMING EVENTS</div><h3>{events.length} Upcoming {events.length===1?'Event':'Events'}</h3>{events.length===0?<p className="muted">No upcoming events have been created for this team.</p>:<div style={{display:'grid',gap:0,marginTop:14}}>{events.map(ev=>{const a=availability[ev.id]||{event_id:ev.id};return <div key={ev.id} style={{display:'grid',gridTemplateColumns:'minmax(240px,1.4fr) minmax(150px,.8fr) minmax(150px,.8fr) auto',gap:18,alignItems:'center',padding:'18px 10px',borderTop:'1px solid #303833'}}><div><strong style={{fontSize:16}}>{ev.title}</strong><div className="muted" style={{marginTop:5}}>{fmt(ev.starts_at)}{ev.ends_at&&` – ${fmt(ev.ends_at)}`} · {ev.location||'Location not recorded'}</div></div><label><span className="muted" style={{display:'block',fontSize:12,marginBottom:5}}>Availability</span><select value={a.availability_status||'not_set'} onChange={e=>updateLocal(ev.id,'availability_status',e.target.value)} style={{width:'100%'}}><option value="not_set">Not Set</option><option value="available">Available</option><option value="maybe">Maybe</option><option value="unavailable">Unavailable</option></select></label><label><span className="muted" style={{display:'block',fontSize:12,marginBottom:5}}>Event Role</span><input value={a.event_role||''} onChange={e=>updateLocal(ev.id,'event_role',e.target.value)} placeholder="e.g. Driver" style={{width:'100%'}}/></label><button className="btn" onClick={()=>save(ev.id)} disabled={saving===ev.id}>{saving===ev.id?'Saving…':'Save'}</button></div>})}</div>}</div></>;
}
