'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';

type Vehicle={id:string;make?:string|null;model?:string|null};
type RaceProfile={competition_number?:string|null};

export default function Engineering(){
 const [vehicle,setVehicle]=useState<Vehicle|null>(null); const [race,setRace]=useState<RaceProfile|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const db=createClient();const {data:{user},error:ue}=await db.auth.getUser();if(ue)throw ue;if(!user)throw new Error('Please sign in');const {data:a,error:ae}=await db.from('core_person_auth').select('person_id').eq('auth_user_id',user.id).maybeSingle();if(ae)throw ae;if(!a)throw new Error('Login is not linked to a Core Person');const {data:m,error:me}=await db.from('organisation_members').select('organisation_id').eq('person_id',a.person_id).eq('membership_status','active').limit(1).maybeSingle();if(me)throw me;if(!m)throw new Error('No active team membership found');const {data:v,error:ve}=await db.from('vehicles').select('id,make,model').eq('organisation_id',m.organisation_id).limit(1).maybeSingle();if(ve)throw ve;setVehicle(v);if(v){const {data:rp,error:rpe}=await db.from('raceiq_vehicle_profiles').select('competition_number').eq('vehicle_id',v.id).maybeSingle();if(rpe)throw rpe;setRace(rp)}}catch(e:any){setError(e.message||'Unable to load engineering')}finally{setLoading(false)}})()},[]);
 const name=vehicle?`${vehicle.make||''} ${vehicle.model||''}${race?.competition_number?` #${race.competition_number}`:''}`.trim():'Vehicle';
 return <><div className="top"><div><div className="eyebrow">Garage / Vehicle / Engineering</div><h1>Engineering</h1><div className="muted">{loading?'Loading vehicle…':error?error:name}</div></div><div className="status">ENGINEERING READY</div></div><section className="grid"><div className="card"><div className="card-label">MAINTENANCE</div><h3>Maintenance</h3><p className="muted">Run, date and time-based service items. Oil, tyres, belts, chain, brakes and scheduled inspections.</p><button className="btn" disabled>Open Maintenance</button></div><div className="card"><div className="card-label">COMPONENTS</div><h3>Component Life</h3><p className="muted">Track component installation, run life, inspection intervals and replacement history.</p><button className="btn" disabled>Open Components</button></div><div className="card"><div className="card-label">RUN COUNTER</div><h3>Vehicle Runs</h3><p className="muted">0 recorded runs<br/>Track Mode will update this automatically.</p></div><div className="card"><div className="card-label">ENGINEERING NOTES</div><h3>Notes</h3><p className="muted">Technical observations, faults, changes and engineering notes for this vehicle.</p><button className="btn" disabled>Open Notes</button></div><div className="card"><div className="card-label">DOCUMENTS</div><h3>Engineering Documents</h3><p className="muted">Technical sheets, manuals, component information and supporting vehicle documents.</p></div><div className="card"><div className="card-label">HISTORY</div><h3>Engineering History</h3><p className="muted">Maintenance, component changes and engineering activity will form the vehicle timeline.</p></div></section><div className="actions"><Link className="btn" href="/garage/vehicle">Back to Vehicle</Link></div></>;
}
